### DISCUSSION TITLE
Async http PUT in loop with reqwest

### DISCUSSION THREAD

**Discussion by mihaigalos** [tokio-rs/tokio#4264] [Q&A] [answered]
In Rust, using `reqwest` and `tokio`, I'm trying to put a file to a http server (nginx, hosted locally).
I would like to have a loop and update a progress bar with the amount of bytes transfered:

```rust
pub async fn put(input: &str, output: &str, _: &WrappedBar) {
    let file = tokio::fs::File::open(input).await.unwrap();
    let stream = tokio_util::codec::FramedRead::new(file, tokio_util::codec::BytesCodec::new());
    let body = reqwest::Body::wrap_stream(stream);

    let _ = reqwest::Client::new()
        .put(output)
        .header("content-type", "application/octet-stream")
        .body(body)
        .send()
        .await
        .unwrap();

    loop {
        let uploaded = file.seek(std::io::SeekFrom::Current(0)).await.unwrap();

        // use the client.body(body).send().await.unwrap() here instead of outside the loop
        // update the progress bar

        if uploaded == file.metadata().await.unwrap().len() {
            break;
        }
    }
}
```
`Cargo.toml`:
```toml
reqwest = { version = "0.11.3", features = ["stream"] }
tokio = { version = "1.14.0", features = ["full"] }
tokio-util = "0.6.9"
```
`file` is moved when constructing the stream, so how can I reuse it here? Is the approach even correct?
