### DISCUSSION TITLE
Wrong tokio runtime when using dlopen

### DISCUSSION THREAD

**Discussion by yang282441848** [tokio-rs/tokio#5299] [Q&A] [answered]
# Scene
I want to use plugins to compose my application by using `dlopen`.
But something goes wrong when I use async function in my plugins like `there is no reactor running, must be called from the context of a Tokio 1.x runtime`

# Code
There are two parts of my poject.
Project **plugin** for library and project **app** for runtime.
## Project Plugin
```toml
# Cargo.toml
[package]
name = "plugin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio={version="1.20", features=["full"]}

[lib]
crate-type = ["cdylib", "rlib"]
```

```rust
// lib.rs
use std::any::Any;

pub trait PluginTrait: Send + Sync + Any {
    fn run(&self);
    fn get_aysnc_fn(&self) -> tokio::time::Sleep;
}

struct Plugin;

impl PluginTrait for Plugin {
    fn run(&self) {
        println!("##Hello##");
    }

    fn get_aysnc_fn(&self) -> tokio::time::Sleep {
        tokio::time::sleep(tokio::time::Duration::from_secs(1))
    }
}

#[no_mangle]
pub extern "C" fn create() -> *mut dyn PluginTrait {
    let object = Plugin {};
    let boxed: Box<dyn PluginTrait> = Box::new(object);
    Box::into_raw(boxed)
}
```

## Project app
```toml
[package]
name = "app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio={version="1.20", features=["full"]}
libloading = "0.7"
```
```rust
// main.rs
use std::any::Any;

use libloading::Symbol;

pub trait PluginTrait: Send + Sync + Any {
    fn run(&self);
    fn get_aysnc_fn(&self) -> tokio::time::Sleep;
}

#[tokio::main]
async fn main() {
    let path = "/Users/mason/code/im/rust/demo/plugin/target/debug/libplugin.dylib";

    println!("sleep before dlopen");
    tokio::time::sleep(tokio::time::Duration::from_secs(1)).await;

    unsafe {
        let lib = libloading::Library::new(path).unwrap();
        type CreateSymbol = extern "C" fn() -> *mut dyn PluginTrait;
        let create_fn: Symbol<CreateSymbol> = lib.get(b"create").unwrap();
        let object = create_fn();
        let object = Box::from_raw(object);
        object.run();

        println!("sleep after dlopen");
        object.get_aysnc_fn().await;

        println!("after sleep");
    }
}
```
# Result
```text
##Hello##
sleep before dlopen
sleep after dlopen
thread '<unnamed>' panicked at 'there is no reactor running, must be called from the context of a Tokio 1.x runtime', src/lib.rs:16:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

# Problem
I don't know the reason why the `timer` exported by plugin cannot work in the main runtime.
These two timers seem to be the same, there are run in the same thread.And got the same result where I use
`tokio::runtime::Builder::new_current_thread().enable_all().build().unwrap()`
instead of `#[tokio::main]`
