### ISSUE TITLE
Unable to run reqwest future with tokio::main

### ISSUE THREAD

**Issue by Nashenas88** [tokio-rs/tokio#1412]
## Version

tokio v0.2.0 (https://github.com/tokio-rs/tokio#2e69f2a7)
(tokio v0.1.22 (*) also shows as a dep for reqwest and hyper)

## Platform

Darwin &lt;Removed for privacy&gt;.local 17.7.0 Darwin Kernel Version 17.7.0: Wed Apr 24 21:17:24 PDT 2019; root:xnu-4570.71.45~1/RELEASE_X86_64 x86_64

## Description

I'm trying to update a project to async/await syntax since it's going to stabilize soon. I'm using the following Cargo.toml:
```toml
[package]
name = "tokio_runtime_test"
version = "0.1.0"
authors = ["Paul Daniel Faria <Nashenas88@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { git = "https://github.com/tokio-rs/tokio" }
reqwest = "0.9.19"
futures-preview = { version = "0.3.0-alpha.17", features = ["compat"] }
futures01 = { package = "futures", version = "0.1.28"} 
```

And this is my `main.rs`:
```rust
#![feature(async_await)]
use futures::compat::Future01CompatExt;
use reqwest::{r#async::{Client, Request}, Method};
use tokio::prelude::*;

#[tokio::main]
async fn main() {
    let request = Request::new(Method::GET, "https://www.google.com/".parse().unwrap());
    let client = Client::new();
    let result = client.execute(request).compat().await;
    println!("Result: {:?}", result);
}
```

Running this returns the following error:
`Result: Err(Error(Hyper(Error(User(Execute), "tokio::spawn failed (is a tokio runtime running this future?)")), "https://www.google.com/"))`

While making this report, I realized that reqwest relies on a different version of tokio than the one I'm using to make `main` async. Is there a way to allow the two to interoperate, or do I need to wait for `reqwest` and `hyper` to update to latest?
