### ISSUE TITLE
Infinite loop in LocalSet drop impl

### ISSUE THREAD

**Issue by swlynch99** [tokio-rs/tokio#1885]
## Version

```
cargo tree | grep tokio
└── tokio v0.2.2
```

## Platform

```
uname -a
Darwin tw-mbp-slynch 18.7.0 Darwin Kernel Version 18.7.0: Sat Oct 12 00:02:19 PDT 2019; root:xnu-4903.278.12~1/RELEASE_X86_64 x86_64
```

```
rustc --version
rustc 1.39.0 (4560ea788 2019-11-04
```

## Description

The following program enters an infinite loop within the `LocalSet` drop impl. I'd expect this not to happen and the program to exit normally.

This issue appears to be specific to `LocalSet` and also requires that the `Sender` part of the channel be dropped before the `Reciever`.
```rust
use std::io::Result;
use std::time::Duration;

use tokio::runtime::Builder;
use tokio::task::LocalSet;
use tokio::time::delay_for;

fn main() -> Result<()> {
    let (send, mut recv) = tokio::sync::mpsc::channel::<()>(1024);

    let mut rt = Builder::new()
        .enable_time()
        .basic_scheduler()
        .build()?;

    let workers = LocalSet::new();
    workers.spawn_local(async move {
        while let Some(_) = recv.recv().await {}
    });
    workers.block_on(&mut rt, async {
        delay_for(Duration::from_secs(1)).await;
    });

    drop(send);

    // This enters an infinite loop
    drop(workers);

    Ok(())
}
```

<details>
<summary>Cargo.toml</summary>

```toml
[package]
name = "mcve"
version = "0.1.0"
edition = "2018"

[dependencies]
tokio = { version = "0.2.2", features = [ "sync", "time", "rt-util", "rt-core" ] }
```
</details>
