### ISSUE TITLE
Assertion failure in steal_into / steal_into2

### ISSUE THREAD

**Issue by jebrosen** [tokio-rs/tokio#2382]
## Description

A "hello_world" using Rocket's async branch is hitting an assertion in `queue.rs`.

## Reproduction

`Cargo.toml`:

```toml
[dependencies]
rocket = { git = "https://github.com/SergioBenitez/Rocket.git", branch = "async" } # As of 2020-04-06 this is rev="78c8ac8"
tokio = "=0.2.16"

[profile.release]
lto = true
codegen-units = 1
```

`main.rs`:

```rust
#![feature(proc_macro_hygiene, decl_macro)]

use rocket::{get, routes};

#[get("/")]
fn hello() -> String {
    "Hello world!".to_string()
}

fn main() {
    rocket::ignite().mount("/", routes![hello]).launch().unwrap();
}
```

Then run `wrk -t20 -c1000 -d1h http://localhost:8000` until it fails.

The following assertion is failing in `queue.rs` in both 0.2.15 and 0.2.16:

```
thread 'tokio-runtime-worker' panicked at 'assertion failed: `(left != right)`
  left: `117`,
 right: `117`', /home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.16/src/runtime/queue.rs:414:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

~~In 0.2.14, (EDIT: I misread something in the code; this was nothing more than the already-fixed issue #2362)~~

## Speculation

So far it has not been been reproduced on 0.2.13, suggesting that 0.2.14 includes the regressed commit. My first guess was that it had to do with the scheduler refactor #2273, but after reviewing the change log I also suspect #2315 since it specifically deals with work-stealing. I will try to bisect to a specific commit, but it is a slow process because it takes some time before the assertion fails.

---

This issue was discovered by @ThouCheese, and we did the initial triage in rocket's IRC channel. All results were collected on Linux on an Intel i7-8750H. I have also been able to reproduce the assertion failure on a few commits, on Linux on an AMD Ryzen 7 3700U.
