### ISSUE TITLE
#[tokio::main] allowing arbitrary return values from main

### ISSUE THREAD

**Issue by SirJosh3917** [tokio-rs/tokio#4635]
**Version**

```toml
[dependencies]
tokio = { version = "1.17.0", features = ["macros", "rt-multi-thread"] }
```

**Platform**

Linux x86_64

**Description**

The following code compiles [playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=9ff40351c6b8470eee115801382c7589)

```rs
#[tokio::main]
async fn main() {
    return 1;
    ;
}
```

The following don't compile, as expected

```rs
#[tokio::main]
async fn main() {
    return 1;
    ()
}

#[tokio::main]
async fn main() {
    return 1;
}

#[tokio::main]
async fn main() {
    1
}
```
