### ISSUE TITLE
Resubscribing to a closed broadcast receiver will hang on a call to `recv`

### ISSUE THREAD

**Issue by nathaniel-daniel** [tokio-rs/tokio#4814]
**Version**
tokio v1.19.2, tokio master (4daeea8cad1ce8e67946bc0e17d499ab304b5ca2)

**Platform**
Windows 10 64 bit

**Description**
Attempting to resubscribe to a closed broadcast receiver will hang on calls to `recv`.

I tried this code:
`Cargo.toml`:
```toml
[package]
name = "tokio-broadcast-bug"
version = "0.0.0"
edition = "2021"

[dependencies]
tokio = { version = "1.19.2", features = ["full"] }
```
`main.rs`:
```rust
#[tokio::main]
async fn main() {
    let (tx, rx) = tokio::sync::broadcast::channel::<u32>(4);
    drop(tx);

    let mut rx_clone = rx.resubscribe();
    drop(rx);

    loop {
        match rx_clone.recv().await {
            Ok(msg) => {
                println!("{}", msg);
            }
            Err(tokio::sync::broadcast::error::RecvError::Closed) => {
                println!("Closed");
                break;
            }
            Err(tokio::sync::broadcast::error::RecvError::Lagged(n)) => {
                println!("Lagged by {n} messages");
            }
        }
    }

    println!("Done");
}
```
I expected to see this happen: 
The loop should exit.

Instead, this happened: 
The program hangs indefinitely. 

Furthermore, replacing the loop with a call to `try_recv` yields an `Empty` error instead of a `Closed` error.
