### ISSUE TITLE
execute future in tokio::spawn causes more memory consumption.

### ISSUE THREAD

**Issue by dream-1ab** [tokio-rs/tokio#7064]
**Version**
Rust: `rustc 1.83.0 (90b35a623 2024-11-26)`
```
PS /media/dreamlab/Development/Project/meshel_customer_service/backend/new/customer_service/target/release> cargo tree | grep tokio
│   │   └── tokio v1.42.0
│   │       └── tokio-macros v2.4.0 (proc-macro)
│   │   ├── tokio v1.42.0 (*)
│   ├── tokio v1.42.0 (*)
│   ├── tokio-tungstenite v0.26.1
│   │   ├── tokio v1.42.0 (*)
│   │   ├── tokio v1.42.0 (*)
│   │   ├── tokio-util v0.7.13
│   │   │   └── tokio v1.42.0 (*)
│   │   └── tokio v1.42.0 (*)
│   │   └── tokio v1.42.0 (*)
│   ├── tokio v1.42.0 (*)
│   ├── tokio-rustls v0.26.1
│   │   └── tokio v1.42.0 (*)
├── tokio v1.42.0 (*)
    │   ├── tokio v1.42.0 (*)
    ├── tokio v1.42.0 (*)
    ├── tokio-util v0.7.13 (*)

```

**Platform**
The output of `uname -a` (UNIX), or version and 32 or 64-bit (Windows)
```
Linux dreamlab-xiaomibookpro162022 6.5.0-1024-oem #25-Ubuntu SMP PREEMPT_DYNAMIC Mon May 20 14:47:48 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```
**Description**

I'm working on a server-side project uses rust + tokio + tower + axum.
suddenly I noticed that my hello world axum http server takes almost 100MB of ram when I run load test with `ab -c 1000 -n 500000 http://0.0.0.0:7999/`
and finally, I found why simple hello world program takes 100MB of ram.
this is caused when I run server initialization inside of tokio::spawn.
it consumes 10x more memory than running without tokio::spawn.

I tried this code:

main.rs
```rust
use std::{future::Future, time::Duration};

use axum::{http::{HeaderName, HeaderValue}, routing::get, Router};
// use axum_extensions::request_counter::RequestCounter;
use tower_http::cors::Any;

mod axum_extensions;

#[tokio::main]
async fn main() {
    let (host, port) = (
        std::env::var("SERVER_HOST").unwrap_or("0.0.0.0".to_string()),
        std::env::var("SERVER_PORT").unwrap_or("7999".to_string()).parse().unwrap_or(7999),
    );

    let app = Router::new()
        .route("/", get(|| async {
            "hello world"
        }))
        // .layer(RequestCounter::new())
        .layer(tower_http::cors::CorsLayer::new().allow_headers(Any).allow_methods(Any).allow_origin(Any))
        .layer(tower_http::set_header::SetResponseHeaderLayer::appending(HeaderName::from_static("developer"), HeaderValue::from_static("Meshel DreamLab software technologies")))
        .layer(tower_http::set_header::SetResponseHeaderLayer::appending(HeaderName::from_static("server"), HeaderValue::from_static("Rust + Tokio + Hyper + Axum")))
    ;

    let task = async move {
        let tcp_server = tokio::net::TcpListener::bind((host, port)).await.unwrap();
        axum::serve(tcp_server, app).await.unwrap();
    };
    
//****************OVER HERE, Switch comment/comment out those two function to try.*******************
    // run_without_spawn(task).await;
    run_with_spawn(task).await;
//***************************************************
}

async fn run_without_spawn<T>(future: impl Future<Output = T>) {
    future.await;
}

async fn run_with_spawn<T: Send + 'static>(future: impl Future<Output = T> + Send + 'static) {
    tokio::spawn(future).await.unwrap();
}

```
Cargo.toml
```toml
[package]
name = "customer_service"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.8.1", features = ["ws"] }
neo4rs = { version = "0.8.0", features = ["json", "serde_json"] }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.134"
tokio = { version = "1.42.0", features = ["full"] }
tower = { version = "0.5.2", features = ["full"] }
tower-http = { version = "0.6.2", features = ["full"] }

```

[code sample that causes the bug]
You can cause the same problem by commenting out ``// run_with_spawn(task).await;` and comment `run_without_spawn(task).await;`
```rust
    //run_without_spawn(task).await;
    run_with_spawn(task).await;
```

## here is expected result: (without using tokio::spawn)

![Screenshot_20250103_021748](https://github.com/user-attachments/assets/dbf99c26-4ae5-42e3-910a-f70c0353197b)

## here is screenshot after 500,000 times load test with `ab -c 1000 -n 500000 http://0.0.0.0:7999/` when use tokio::spawn 
![Screenshot_20250103_021701](https://github.com/user-attachments/assets/67b177dd-400b-4d5b-88fe-dd0a0520788c)

and memory never goes back to normal (meaning around 10MB).
