### ISSUE TITLE
Investigate testing for API backwards compat using rust-semverver

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/tokio#918]
The tool is under development, but it might be a good idea to try using it:

https://github.com/rust-dev-tools/rust-semverver

**Comment by carlosb1** [comment]
Do you have some idea about how integrate it in tokio?

**Comment by carllerche** [comment]
I do not. I have done no investigation.

The goal is: automated testing should catch API regressions.

**Comment by carlosb1** [comment]
I will play with the tool and how integrate it. Anyway, following the installation process, it crashed in my laptop: https://github.com/rust-dev-tools/rust-semverver/issues/69

**Comment by ibabushkin** [comment]
> Do you have some idea about how integrate it in tokio?

I do! Essentially, you can integrate the tool to run in your CI setup (or run it manually previous to a release) and see whether its input indicates something different than you would expect.

As a caveat, the tool has some issues with more advanced typesystem stuff, but most basic things work as one would expect. Especially if you review the output by hand, the guideline you get is quite useful already.

**Comment by carlosb1** [comment]
I did some tests with azure and the output for the tokio crate is very verbose https://pastebin.com/raw/3snMSAhj and it throws 56 errors. Also, I did an possible azure script from tokio CI scripts. 

```
jobs:
# Check formatting
- job: ${{ parameters.name }}
  displayName: Check semverver
  pool:
    vmImage: ubuntu-16.04
  steps:
    - template: azure-install-rust.yml
      parameters:
        rust_version: nightly
    - script: |
        rustup update nightly
        cargo +nightly install semverver -f
      displayName: Install semverver
    - script: |
        cd tokio 
        cargo semver &>  ../semver_out
        cd ..
        (head -n 1 semver_out | grep "\n -> $current_version") || (echo "versioning mismatch" && exit 1) 
      displayName: Applying semverver

```
I used the rust-sermverve example to integrate CI.
